%YAML:1.0
---
pyramid_levels: 1
template_pyramids:
   -
      template_id: 0
      template_width: 240
      template_height: 134
      features:
         - [ 36, 99, 5 ]
         - [ 52, 109, 5 ]
         - [ 217, 56, 0 ]
         - [ 217, 42, 0 ]
         - [ 10, 81, 7 ]
         - [ 8, 68, 0 ]
         - [ 8, 31, 0 ]
         - [ 186, 109, 3 ]
         - [ 177, 97, 3 ]
         - [ 36, 25, 4 ]
         - [ 74, 121, 5 ]
         - [ 167, 121, 3 ]
         - [ 231, 75, 0 ]
         - [ 25, 93, 5 ]
         - [ 8, 52, 0 ]
         - [ 224, 87, 2 ]
         - [ 191, 25, 4 ]
         - [ 63, 25, 4 ]
         - [ 83, 25, 4 ]
         - [ 22, 63, 0 ]
         - [ 182, 11, 4 ]
         - [ 143, 25, 4 ]
         - [ 99, 102, 7 ]
         - [ 22, 42, 0 ]
         - [ 74, 97, 3 ]
         - [ 86, 93, 4 ]
         - [ 129, 25, 4 ]
         - [ 206, 26, 4 ]
         - [ 144, 11, 4 ]
         - [ 161, 11, 4 ]
         - [ 42, 121, 4 ]
         - [ 215, 73, 1 ]
         - [ 179, 132, 1 ]
         - [ 231, 48, 0 ]
         - [ 10, 18, 1 ]
         - [ 18, 121, 4 ]
         - [ 101, 25, 4 ]
         - [ 127, 11, 4 ]
         - [ 42, 86, 5 ]
         - [ 59, 129, 6 ]
         - [ 113, 25, 4 ]
         - [ 35, 11, 4 ]
         - [ 236, 122, 4 ]
         - [ 47, 10, 4 ]
         - [ 102, 10, 4 ]
         - [ 196, 121, 4 ]
         - [ 54, 93, 6 ]
         - [ 231, 31, 0 ]
         - [ 62, 11, 4 ]
         - [ 213, 121, 4 ]
         - [ 78, 11, 4 ]
         - [ 211, 11, 4 ]
         - [ 198, 11, 4 ]
         - [ 208, 96, 3 ]
         - [ 203, 82, 3 ]
         - [ 225, 15, 6 ]
         - [ 139, 101, 1 ]
         - [ 92, 123, 3 ]
         - [ 145, 122, 5 ]
         - [ 154, 91, 4 ]
         - [ 47, 25, 4 ]
         - [ 23, 31, 0 ]
         - [ 196, 103, 3 ]
         - [ 91, 11, 4 ]
         - [ 31, 121, 4 ]
